fail_fast: true
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
      -   id: detect-private-key
      -   id: trailing-whitespace
      -   id: check-added-large-files
      -   id: check-yaml
    # - repo: https://github.com/jumanjihouse/pre-commit-hooks
    #   rev: v3.0.0
    #   hooks:
    #   -   id: markdownlint
    # -   repo: git://github.com/detailyang/pre-commit-shell
    #     rev: v1.0.6
    #     hooks:
    #     - id: shell-lint
    #       args: [--format=json]
    # - repo: https://github.com/lovesegfault/beautysh
    #   rev: 6.2.1
    #   hooks:
    #   -   id: beautysh
    # - repo: https://github.com/Koihik/LuaFormatter
    #   rev: v1.3.6
    #   hooks:
    #   -   id: luaformatter
    # - repo: https://github.com/Calinou/pre-commit-luacheck
    #   rev: v1.0.0
    #   hooks:
    #   -   id: luacheck
    # - repo: https://github.com/zricethezav/gitleaks
    #   rev: 8.12.0
    #   hooks:
    #   -   id: gitleaks
